[package]
name = "adrastea"
version = "0.1.0"
edition = "2021"
authors = ["Adrastea Authors <adrastea@str.rs>"]
description = "Software 3.11 for Workgroups"
license = "AGPL-3.0-only"

[dependencies]
ash = { version = "0.37.2", features = ["loaded"] }

[target.'cfg(windows)'.dependencies]
windows = "0.48.0"

[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"
