[package]
name = "adrastea"
version = "0.1.0"
edition = "2021"
authors = ["Adrastea Authors <adrastea@str.rs>"]
description = "Software 3.11 for Workgroups"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.71"
ash = { version = "0.37.2", features = ["loaded"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
simt_cuda_sys = "0.1.0"
simt_hip_sys = "0.1.1"

adrastea_kernels = { path = "../adrastea_kernels" }

[target.'cfg(windows)'.dependencies]
windows = "0.48.0"
