[package]
name = "adrastea"
version = "0.1.0"
edition = "2021"
authors = ["Adrastea Authors <adrastea@str.rs>"]
description = "Software 3.11 for Workgroups"
license = "AGPL-3.0-only"

[features]
hip = ["adrastea_kernels/hip"]

[dependencies]
adrastea_kernels = { path = "../adrastea_kernels" }

anyhow = "1.0.71"
ash = { version = "0.37.2", features = ["loaded"] }
half = "2"
memmap2 = "0.6.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-pickle = "1.1.1"
simt_cuda_sys = "0.1.1"
simt_hip = "0.1.2"
simt_hip_sys = "0.1.2"
zip = { version = "0.6.6", default-features = false, features = [] }

[target.'cfg(windows)'.dependencies]
windows = "0.48.0"
