[package]
name = "adrastea"
version = "0.1.0"
edition = "2021"
authors = ["Adrastea Authors <adrastea@str.rs>"]
description = "Software 3.11 for Workgroups"
license = "AGPL-3.0-only"

[features]
hip = ["adrastea_kernels/hip"]

[dependencies]
adrastea_kernels = { path = "../adrastea_kernels" }

anyhow = "1.0.71"
ash = { version = "0.37.2", features = ["loaded"] }
half = "2"
libspa-sys = "0.6.0"
matrixmultiply = { version = "0.3.7", features = ["threading"] }
memmap2 = "0.6.1"
num-traits = "0.2.15"
parking_lot = "0.12.1"
pipewire = "0.6.0"
rustfft = "6.1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-pickle = "1.1.1"
simt_cuda_sys = "0.1.1"
simt_hip = "0.1.6"
simt_hip_sys = "0.1.2"
simt_rocblas_sys = "0.1.0"
smallvec = "1.10.0"
tiktoken-rs = "0.4.2"
wav = "1.0.0"
zip = { version = "0.6.6", default-features = false, features = [] }
pipewire-sys = "0.6.0"
allocator-api2 = "0.2.14"
libc = "0.2.146"
wayland-client = "0.30.2"
wayland-server = "0.30.1"
wayland-protocols = { version = "0.30.0", features = ["client", "unstable"] }
wayland-protocols-wlr = { version = "0.1.0", features = ["client"] }
cstr = "0.2.11"
skia-safe = "0.63.0"
sentencepiece = "0.11.1"
skia-bindings = "0.63.0"
regex = "1.8.4"
bstr = "1.5.0"
byteorder = "1.4.3"
clap = { version = "4.3.10", features = ["derive"] }

[target.'cfg(windows)'.dependencies]
windows = "0.48.0"
